version: "3"
networks:
  default:
    driver: bridge
services:
  jaeger:
    image: jaegertracing/all-in-one:1.34
    container_name: jaeger
    restart: always
    networks:
      - default
    ports:
      - "16686:16686"

  consul:
    image: consul
    container_name: consul
    restart: always
    networks:
      - default
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap -ui -node=1 -client='0.0.0.0'"

  front:
    image: front:v1
    networks:
      - default
    ports:
      - "8001:8001"
    depends_on:
      - consul

  sample1:
    image: sample:v1
    networks:
      - default
    depends_on:
      - consul
  
  sample2:
    image: sample:v1
    networks:
      - default
    depends_on:
      - consul

  sample3:
    image: sample:v1
    networks:
      - default
    depends_on:
      - consul